### ISSUE TITLE
Rule 42: contactPoint can be a blank node

### ISSUE THREAD

**Issue by ziodave** [EmidioStani/dcat-ap_validator#1]
Hello,

The following rule:

```sparql
# Rule_ID:42
  {SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s ?p ?o
   WHERE {
     ?s a dcat:Dataset.
     ?s adms:contactPoint ?o.
     FILTER(!isURI(?o)).
     BIND (adms:contactPoint AS ?p).
     BIND ("Dataset" AS ?Class_Name).
     BIND (42 AS ?Rule_ID).
     BIND ("error" AS ?Rule_Severity).
     BIND ("adms:contactPoint should be a resource." AS ?Rule_Description).
     BIND (concat("The adms:contactPoint ",str(?o)," is not a resource.") AS ?Message).
   }
  }
```

requires all contact points to be URIs, but a contact point might also be defined as a _blank node_ reference.

Therefore I would suggest updating the rule filter to:

```sparql
     FILTER(!isURI(?o) && !isBlank(?o)).
```

WDYT?

**Comment by EmidioStani** [comment]
Rule 42 has been removed and many others indicated as URI, only few of them are left accordingly to specifications (rule [80](../rules/rule-80.rq), [90](https://github.com/EmidioStani/dcat-ap_validator/blob/master/rules/rule-90.rq), [124](https://github.com/EmidioStani/dcat-ap_validator/blob/master/rules/rule-124.rq), [155](https://github.com/EmidioStani/dcat-ap_validator/blob/master/rules/rule-155.rq)).
