### ISSUE TITLE
Rule 51: publisher must be URI

### ISSUE THREAD

**Issue by ziodave** [EmidioStani/dcat-ap_validator#2]
Hello,

The following rule:

```sparql
# Rule_ID:51
  {SELECT ?Class_Name ?Rule_ID ?Rule_Severity ?Rule_Description ?Message ?s (dct:publisher as ?p) ?o 
   WHERE {
     ?s a dcat:Dataset.
     ?s dct:publisher ?o.
     FILTER(!isURI(?o)).
     BIND ("Dataset" AS ?Class_Name).
     BIND (51 AS ?Rule_ID).
     BIND ("error" AS ?Rule_Severity).
     BIND ("dct:publisher should be a resource." AS ?Rule_Description).
     BIND (concat("The dct:publisher ",str(?o)," is not a resource.") AS ?Message).
   }
  }
```

which doesn't match _blank nodes_.

I think the _filter_ should be changed to

```sparql
    FILTER(!isURI(?o) && !isBlank(?o)).
```

**Comment by EmidioStani** [comment]
Rule 51 has been removed and many others indicated as URI, only few of them are left accordingly to specifications (rule [80](../rules/rule-80.rq), [90](https://github.com/EmidioStani/dcat-ap_validator/blob/master/rules/rule-90.rq), [124](https://github.com/EmidioStani/dcat-ap_validator/blob/master/rules/rule-124.rq), [155](https://github.com/EmidioStani/dcat-ap_validator/blob/master/rules/rule-155.rq)).
