### ISSUE TITLE
build fails on Mac OS X

### ISSUE THREAD

**Issue by ziodave** [EmidioStani/dcat-ap_validator#3]
`ant` fails on Mac OS X with the following error:

```
dcat-ap_validator/build.xml:158: Execute failed: java.io.IOException: Cannot run program "cmd.exe": error=2, No such file or directory
```

Is the build compatible with Windows only?

Thanks

**Comment by EmidioStani** [comment]
Fixed within commit: https://github.com/EmidioStani/dcat-ap_validator/commit/78c6b6156e42d76b1538d23ae8edb13cdd391e9b
